version: 2

jobs:
  build:
    working_directory: ~/gitrevue-sdk-js

    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Compile typescript
          command: npm run build

      - run:
          name: Linting
          command: npm run lint

      - run:
          name: Jest
          command: npm test

workflows:
  version: 2

  build:
    jobs:
      - build
